name: Docker

on: [push, pull_request]

jobs:

  create-carla-prerequisites-image:
    name: create carla prerequisites image
    runs-on: self-hosted
    steps:
      - uses: docker/setup-buildx-action@v3
        name: Set up Docker Buildx
      - uses: docker/login-action@v3
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        name: Build and push
        with:
          file: Util/Docker/Prerequisites.Dockerfile
          build-args: |
            EPIC_USER=${{ secrets.EPIC_USER }}
            EPIC_PASS=${{ secrets.EPIC_PASS }}
          tags: carla-prerequisites
          outputs: type=docker,dest=/tmp/carla-prerequisites.tar
      - uses: actions/upload-artifact@v3
        name: Upload artifact
        with:
          name: carla-prerequisites
          path: /tmp/carla-prerequisites.tar

  create-carla-source-image:
    name: create carla source image
    runs-on: self-hosted
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: carla-prerequisites
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/carla-prerequisites.tar
          docker image ls -a    
      - uses: docker/login-action@v3
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        name: Build and push
        with:
          push: true
          file: Util/Docker/Carla.Dockerfile
          tags: cgellerac/carla-source
      - uses: shrink/actions-docker-extract@v3
        name: extract carla package
        with:
          image: cgellerac/carla-source
          output: /home/carla/Dist/*.tar.gz
          destination: /tmp/carla-package.tar.gz
      - uses: actions/upload-artifact@v3
        name: Upload artifact
        with:
          name: carla-package
          path: /tmp/carla-package.tar.gz

  create-carla-image:
    name: create carla image
    runs-on: self-hosted
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: carla-package
          path: /tmp
      - name: Extract artifact
        run: tar -xvzf /tmp/carla-package.tar.gz -C /build 
      - uses: docker/login-action@v3
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        name: Build and push
        with:
          push: true
          file: /build/Dockerfile
          context: /build
          tags: cgellerac/carla