name: Docker

on: [push, pull_request]

jobs:

  # create carla-prerequisites image
  create-carla-prerequisites-image:
    name: Create carla-prerequisites image
    runs-on: self-hosted
    steps:
  
      - uses: docker/build-push-action@v5
        name: Build image
        with:
          file: Util/Docker/Prerequisites.Dockerfile
          tags: carla-prerequisites
          build-args: |
            EPIC_USER=${{ secrets.EPIC_USER }}
            EPIC_PASS=${{ secrets.EPIC_PASS }}

  # create and push carla-source image
  create-carla-source-image:
    name: Create carla-source image
    runs-on: self-hosted
    #needs: create-carla-prerequisites-image
    steps:
    
      - uses: docker/login-action@v3
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v5
        name: Build and push image
        with:
          file: Util/Docker/Carla.Dockerfile
          tags: cgellerac/carla-source
          push: true

  # provide artifacts and releases
  provide-artifacts:
    name: Provide carla artifacts
    runs-on: self-hosted
    needs: create-carla-source-image
    steps:

      # provide carla-package
      - uses: shrink/actions-docker-extract@v3
        name: Extract carla-package
        id: extract_carla_package
        with:
          image: cgellerac/carla-source
          path: /home/carla/Dist
          destination: /tmp/

      - uses: actions/upload-artifact@v3
        name: Upload carla-package
        with:
          name: carla-package
          path: ${{ steps.extract_carla_package.outputs.destination }}

      # provide carla-python-api
      - uses: shrink/actions-docker-extract@v3
        name: Extract carla-python-api
        id: extract_python_api
        with:
          image: cgellerac/carla-source
          path: /home/carla/PythonAPI
          destination: /tmp/

      - uses: actions/upload-artifact@v3
        name: Upload carla-python-api
        with:
          name: carla-python-api
          path: ${{ steps.extract_python_api.outputs.destination }}

      # provide release
      - uses: ncipollo/release-action@v1
        name: Create Release
        if: startsWith(github.ref, 'refs/tags')
        with:
          allowUpdates: true
          tag: ${{ github.ref_name }}
          commit: ${{ github.sha }}
          artifacts: "${{ steps.extract_python_api.outputs.destination }}"
          token: ${{ secrets.PAT }}

  # create and push carla image
  create-carla-image:
    name: Create carla image
    runs-on: self-hosted
    needs: provide-artifacts
    steps:

      - uses: docker/login-action@v3
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Download carla-package
        uses: actions/download-artifact@v3
        with:
          name: carla-package
          path: /tmp

      - name: Extract artifact
        run: tar -xvzf /tmp/carla-package.tar.gz -C /build

      - uses: docker/build-push-action@v5
        name: Build and push
        with:
          file: /build/Dockerfile
          tags: cgellerac/carla
          context: /build
          push: true  