name: Docker

on: [push, pull_request]

jobs:

  clean-up:
    name: Clean up
    runs-on: self-hosted
    steps:

      - name: Clean up
        run: rm -rf *
        
  # create carla-prerequisites image
  create-carla-prerequisites-image:
    name: Create carla-prerequisites image
    runs-on: self-hosted
    needs: clean-up
    steps:

      - uses: docker/build-push-action@v5
        name: Build image
        with:
          file: Util/Docker/Prerequisites.Dockerfile
          tags: carla-prerequisites
          build-args: |
            EPIC_USER=${{ secrets.EPIC_USER }}
            EPIC_PASS=${{ secrets.EPIC_PASS }}
            
  # create and push carla-source image
  create-carla-source-image:
    name: Create carla-source image
    runs-on: self-hosted
    needs: create-carla-prerequisites-image
    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: docker/login-action@v3
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v5
        name: Build and push image
        with:
          file: Util/Docker/Carla.Dockerfile
          tags: cgellerac/carla-source
          push: true
          context: .
          
  # provide artifacts and releases
  provide-artifacts:
    name: Provide carla artifacts
    runs-on: self-hosted
    needs: create-carla-source-image
    steps:

      # provide carla-package
      - uses: shrink/actions-docker-extract@v3
        name: Extract carla-package
        with:
          image: cgellerac/carla-source
          path: home/carla/carla/Dist
          destination: artifacts/

      - name: Keep only .tar.gz archive 
        run: rm -rf artifacts/Dist/CARLA_Shipping_*

      #- uses: actions/upload-artifact@v3
      #  name: Upload carla-package
      #  with:
      #    name: carla-package
      #    path: artifacts/Dist

      # provide carla-python-api
      - uses: shrink/actions-docker-extract@v3
        name: Extract carla-python-api
        id: extract_python_api
        with:
          image: cgellerac/carla-source
          path: home/carla/carla/PythonAPI
          destination: artifacts/

      #- uses: actions/upload-artifact@v3
      #  name: Upload carla-python-api
      #  with:
      #    name: carla-python-api
      #    path: artifacts/PythonAPI

      # provide release
      - uses: ncipollo/release-action@v1
        name: Create Release
        if: startsWith(github.ref, 'refs/tags')
        with:
          allowUpdates: true
          tag: ${{ github.ref_name }}
          commit: ${{ github.sha }}
          artifacts: artifacts/PythonAPI
          token: ${{ secrets.PAT }}
          
  # create and push carla image
  create-carla-image:
    name: Create carla image
    runs-on: self-hosted
    needs: provide-artifacts
    steps:
    
      - uses: docker/login-action@v3
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      #- name: Download carla-package
      #  uses: actions/download-artifact@v3
      #  with:
      #    name: carla-package
      #    path: artifacts

      - name: Extract artifact
        run: tar -xvzf artifacts/Dist/*.tar.gz -C build

      - uses: docker/build-push-action@v5
        name: Build and push
        with:
          file: build/Dockerfile
          tags: cgellerac/carla
          context: build
          push: true  
