name: Docker

on: [push, pull_request]

jobs:

  # provide artifacts and releases
  provide-artifacts:
    name: Provide carla artifacts
    runs-on: self-hosted
    #needs: create-carla-source-image
    steps:

      # provide carla-package
      - uses: shrink/actions-docker-extract@v3
        name: Extract carla-package
        with:
          image: cgellerac/carla-source
          path: home/carla/carla/Dist
          destination: /tmp/

      - name: test1
        run: pwd

      - name: test2
        run: ls
        
      - name: test3
        run: ls /tmp
        
      - name: test4
        run: echo ${{ steps.extract_carla_package.outputs.destination }}
        
      # provide carla-python-api
      - uses: shrink/actions-docker-extract@v3
        name: Extract carla-python-api
        id: extract_python_api
        with:
          image: cgellerac/carla-source
          path: home/carla/carla/PythonAPI
          destination: /tmp/

      - name: test5
        run: pwd

      - name: test6
        run: ls
        
      - name: test7
        run: ls /tmp 
        
      - name: test8
        run: echo ${{ steps.extract_python_api.outputs.destination }}


        
      - uses: actions/upload-artifact@v3
        name: Upload carla-package
        with:
          name: carla-package
          path: ${{ steps.extract_carla_package.outputs.destination }}

      - uses: actions/upload-artifact@v3
        name: Upload carla-python-api
        with:
          name: carla-python-api
          path: ${{ steps.extract_python_api.outputs.destination }}

      # provide release
      - uses: ncipollo/release-action@v1
        name: Create Release
        if: startsWith(github.ref, 'refs/tags')
        with:
          allowUpdates: true
          tag: ${{ github.ref_name }}
          commit: ${{ github.sha }}
          artifacts: "${{ steps.extract_python_api.outputs.destination }}"
          token: ${{ secrets.PAT }}

  # create and push carla image
  create-carla-image:
    name: Create carla image
    runs-on: self-hosted
    needs: provide-artifacts
    steps:

      - uses: docker/login-action@v3
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Download carla-package
        uses: actions/download-artifact@v3
        with:
          name: carla-package
          path: /tmp

      - name: debug
        run: ls -la /tmp
        
      - name: Extract artifact
        run: tar -xvzf /tmp/carla-package.tar.gz -C /build

      - uses: docker/build-push-action@v5
        name: Build and push
        with:
          file: /build/Dockerfile
          tags: cgellerac/carla
          context: /build
          push: true  
