name: Docker

on: [push, pull_request]

jobs:

  # create and push carla image
  create-carla-image:
    name: Create carla image
    runs-on: self-hosted
    #needs: provide-artifacts
    steps:

      - uses: docker/login-action@v3
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      #- name: Download carla-package
      #  uses: actions/download-artifact@v3
      #  with:
      #    name: carla-package
      #    path: artifacts

      - name: debug
        run: ls -la artifacts
        
      - name: Extract artifact
        run: mkdir build && tar -xvzf artifacts/*.tar.gz -C build

      - name: debug3
        run: ls -la build

      - uses: docker/build-push-action@v5
        name: Build and push
        with:
          file: build/Dockerfile
          tags: cgellerac/carla
          context: build
          push: true  
